addons:
  apt:
    packages:
    - freeglut3
    - freeglut3-dev
before_install:
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24
script:
  - deps/travissbcl --script bin/travis.lisp
